export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";

export const LAY_THONG_TIN_NGUOI_DUNG_ACTION = "LAY_THONG_TIN_NGUOI_DUNG_ACTION";

export const DANG_XUAT = "DANG_XUAT";

export const LAY_DANH_SACH_NGUOI_DUNG = "LAY_DANH_SACH_NGUOI_DUNG";

export const TIM_KIEM_NGUOI_DUNG = "TIM_KIEM_NGUOI_DUNG";