export const LAY_THONG_TIN_DAT_VE = "LAY_THONG_TIN_DAT_VE";

export const DANG_THONG_TIN_DAT_VE = "DANG_THONG_TIN_DAT_VE";

export const DAT_VE = "DAT_VE";

export const DAT_VE_HOAN_TAT = "DAT_VE_HOAN_TAT";

export const CHUYEN_TAB_DONE = "CHUYEN_TAB_DONE";

export const CHUYEN_TAB_FLEXIBLE = "CHUYEN_TAB_FLEXIBLE";

export const DAT_VE_REAL_TIME = 'DAT_VE_REAL_TIME';